### GET STUDENTS
GET http://localhost:3000/students

### CREATE STUDENT
POST http://localhost:3000/students 
Content-Type: application/json

{
  "first_name": "John",
  "last_name": "Doe",
  "email": "john.doe@example.com",
  "age": 20,
  "course": "BSIT",
  "year_level": 3,
  "gpa": 3.8,
  "enrollment_status": "Active"
}

### UPDATE STUDENT
PUT http://localhost:3000/students/1
Content-Type: application/json

{
  "first_name": "Ernesto",
  "last_name": "Smith",
  "email": "ernesto@example.com",
  "age": 25,
  "course": "Computer Science",
  "year_level": 3,
  "gpa": 3.8,
  "enrollment_status": "Active"
} 

### DELETE STUDENT
DELETE http://localhost:3000/students/1