### GET STUDENTS
GET http://localhost:3000/students/2

### CREATE STUDENT
POST http://localhost:3000/students
Content-Type: application/json

{
  "first_name": "Shayne",
  "last_name": "Doe",
  "email": "shyn.doe@example.com",
  "age": 20,
  "course": "BSIT",
  "year_level": 2,
  "gpa": 3.50,
  "enrollment_status": "Active"
}

### UPDATE STUDENT
PUT http://localhost:3000/students/1
Content-Type: application/json

{
  "first_name": "Ernesto",
  "last_name": "Dela Cruz",
  "email": "ernesto@example.com",
  "age": 26,
  "course": "BSCS",
  "year_level": 3,
  "gpa": 1.80,
  "enrollment_status": "Active"
}

### DELETE STUDENT
DELETE http://localhost:3000/students/23